---
- name:  Restore playbook
  hosts: web1
  tasks:
    # 1) 방화벽 닫기 - http
    # 2) 서비스 내리기 - firewalld, httpd
    # 3) 웹서비스 설정 삭제 - 
    # * /var/www/html/index.html
    # 4) 패키지 삭제 - httpd, firewalld
    # 5) 팩트 삭제 - /etc/ansible/facts.d/
    - name: 1) 방화벽 닫기 - http
      firewalld:
        service: http
        permanent: no
        immediate: no
        state: disabled
    - name: 2) 서비스 내리기 - firewalld, httpd, maraiadb
      service:
        name: "{{ item }}"
        state: stopped
      with_items:
        - firewalld
        - httpd
        - mariadb
    - name: 3) 웹서비스 설정 삭제 - * /var/www/html/index.html
      file:
        path: /var/www/html/index.html
        state: absent
    - name: 4) 패키지 삭제 - httpd, firewalld
      yum:
        name: 
          - httpd
          - firewalld
        state: absent
    - name: 5) 팩트 삭제 - /etc/ansible/facts.d/
      file:
        path: /etc/ansible/facts.d/
        state: absent


