---
- name: 방화벽, 웹서버 설정  
  hosts: all
  tasks:
  # 1) 서비스 기동 - httpd, firewalld
  # 2) 서비스 설정 파일 삭제 - /var/www/html/index.html
  # 3) 패키지 삭제 - httpd, mod_ssl, firewalld
    - name: 웹 서비스 종료
      service:
        name: httpd
        state: absent
      
    - name: 웹 서비스 설정 파일 삭제
      file:
        path: /var/www/html/index.html
        state: absent
    - name: 패키지 삭제
      yum:
        name:
        - httpd
        - mod_ssl
        - firewalld
        state: absent