---
- name: Restore playbook.yml
  hosts: all
  gather_facts: no
  tasks:
    - name: Stop db_service
      service:
        name: mariadb
        state: stopped
        enabled: no
    - name: Uninstall package
      yum:
        name: 
        - mariadb-server
        - httpd
        state: absent
  
  