---
- name: Restore playbook.yml
  hosts: all
  tasks:
    - name: (1) DB 서비스 종료
      service:
        name: mariadb
        state: stopped
        enabled: no

    - name: (2) DB 패키지 삭제
      yum:
        name: 
          - maria-server
          - python3-PyMySQL
        state: absent